"""
Even Fibonacci Numbers
https://projecteuler.net/problem=2
Problem 2
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 
 and 
, the first 
 terms will be:

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

The first 10 terms of the sequence are:
0 1 1 2 3 5 8 13 21 34 55
"""

fib_num_x = 0
fib_num_y = 1
fib_num_z = fib_num_x+fib_num_y

print(f"fib_num_x = {fib_num_x} and fib_num_y = {fib_num_y} and fib_num_z = {fib_num_z}")
print(f"next term in Fib sequence is fib_num_z = {fib_num_x} + {fib_num_y} = {fib_num_x+fib_num_y}")

for i in range(100):
    #print(f"BEFORE ASSIGN >>> fib_num_x = {fib_num_x} and fib_num_y = {fib_num_y} and fib_num_z = {fib_num_z}")
    fib_num_x = fib_num_y
    fib_num_y = fib_num_z
    fib_num_z = fib_num_x + fib_num_y
    #print(f"AFTER ASSIGN >>> fib_num_x = {fib_num_x} and fib_num_y = {fib_num_y} and fib_num_z = {fib_num_z}")
    #print(f"next term in Fib sequence is fib_num_z = {fib_num_x} + {fib_num_y} = {fib_num_z}")
    print(f"f[{i}] = {fib_num_x} and f[{i+1}] = {fib_num_y} and f[{i+2}] = {fib_num_z}")

    if fib_num_z%2 == 0:
        print(f"this term is even f[{i+2}] = {fib_num_z}")
    else:
        print(f"this term is not even f[{i+2}] = {fib_num_z}")
